version: "3.8"
services:
  api:
    build:
      context: ./api
    networks:
      - private
  react:
    build:
      context: ./react
    networks:
      - public
      - private
    depends_on:
      - api
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      - public
      - private
    depends_on:
      - react
networks:
  public:
  private:
volumes:
  postgres_data: