# Generated by Django 4.1.7 on 2023-02-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contact_budget_alter_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='budget',
        ),
    ]
