# Generated by Django 4.1.7 on 2023-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_contact_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
