# Generated by Django 4.1.7 on 2023-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget lv.'),
        ),
    ]
